### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by kspepko** [Lucky1376/ORION-Bomber#5]
Е

**Comment by Lucky1376** [comment]
Очень жаль, но мы полностью прекратили поддержку программы не говоря уже про конкретную OS, мы давно выпустили приложение для Android которое можно установить в Telegram канале. Спасибо за ваш вопрос и интерес к программе

**Comment by While402** [comment]
логичные проблемы у тебя с головой, явно

**Comment by bulbah** [comment]
Зачилься браток

пт, 6 дек. 2024 г., 17:08 Вайл ***@***.***>:
